---
#
# Infrastructure
#
- name: Setup EC2 Infrastructure
  hosts: localhost
  gather_facts: false
  connection: local
  tags: start

  vars_files:
    - "region/janus-{{ aws_region }}-{{ env_name }}.yml"

  roles:
    - janus-create-vpc
    - janus-create-sg
    - janus-create-key
    - janus-create-instances

#
# Janus Configuration
# NB: Hosts are populated from previous task and setup to provide private ip address information
#
- name: Setup Janus Configuration
  hosts: "{{ env.cluster_name }}"
  serial: "{{ env.zones|sum(attribute='servers') }}"
  gather_facts: true
  tags: setup

  vars_files:
    - "region/janus-{{ aws_region }}-{{ env_name }}.yml"

  roles:
    - { role: janus-install, version: 0.1.1 }
