---
janus_version: 0.1.1
janus_dir: "janusgraph-{{ janus_version }}-hadoop2"
janus_download_url: "https://github.com/JanusGraph/janusgraph/releases/download/v{{ janus_version }}/janusgraph-{{ janus_version }}-hadoop2.zip"
janus_download_file: "/tmp/{{ janus_dir }}.zip"
janus_install_prefix: /opt
janus_install_dir: "{{ janus_install_prefix }}/{{ janus_dir }}"
janus_symlink: /opt/janus
janus_system_packages:
  - xfsprogs
  - lvm2
  - unzip
  - java-1.8.0-openjdk
  - java-1.8.0-openjdk-devel
  - dstat
janus_system_packages_remove:
  - java-1.7.0-openjdk
  - java-1.7.0-openjdk-devel

data_mount: /data
data_pv_disk: /dev/xvdb
data_vg_name: data
data_lv_name: data

cassandra_replication: 1
cassandra_quorum: "{{ '%d'|format( (cassandra_replication*(env.zones|length)/2)+1 |round(method='floor')) }}"
elasticsearch_replicas: "{{ '%d'|format(groups[cluster_group]|length / 4) if groups[cluster_group]|length > 4 else 1 }}"
