---
janus_version: 0.1.1
janus_dir: "janusgraph-{{ janus_version }}-hadoop2"
janus_download_url: "https://github.com/JanusGraph/janusgraph/releases/download/v{{ janus_version }}/janusgraph-{{ janus_version }}-hadoop2.zip"
janus_download_file: "/tmp/{{ janus_dir }}.zip"
janus_install_prefix: /opt
janus_install_dir: "{{ janus_install_prefix }}/{{ janus_dir }}"
janus_system_packages:
  - unzip
  - java
