---
- name: Install required system packages
  become: true
  package:
    name: "{{ item }}"
  with_items: "{{ janus_system_packages }}"

- name: Remove unwanted system packages
  become: true
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ janus_system_packages_remove }}"

- name: Create LVM physical device and group
  become: true
  lvg:
    pvs: "{{ data_pv_disk }}"
    vg: "{{ data_vg_name }}"

- name: Create LVM logical volume
  become: true
  lvol: vg={{ data_vg_name }} lv={{ data_lv_name }} size="100%VG"

- name: Create LVM logical volume filesystem
  become: true
  filesystem: fstype=xfs dev=/dev/{{ data_vg_name }}/{{ data_lv_name }}

- name: Create mount point
  become: true
  file: path={{ data_mount }} state=directory owner={{ ansible_user }} group={{ ansible_user}}

- name: Mounting data filesystem
  become: true
  mount: name={{ data_mount }} src=/dev/{{ data_vg_name }}/{{ data_lv_name }} fstype=xfs state=mounted

- name: Ensure we own the data disk
  become: true
  file: path={{ data_mount }} state=directory owner={{ ansible_user }} group={{ ansible_user}}

- name: Download JanusGraph
  get_url:
    url: "{{ janus_download_url }}"
    dest: "{{ janus_download_file }}"
    checksum: md5:3b97513abc57af6e7fd52cb2b8a5ebaa

- name: Create install dir
  become: true
  file:
    path: "{{ janus_install_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Extract JanusGraph
  unarchive:
    src: "{{ janus_download_file }}"
    dest: "{{ janus_install_prefix }}"
    remote_src: yes
    #copy: no
    creates: "{{ janus_install_dir }}/CHANGELOG.asc"

- name: Symlink for ease of use
  become: true
  file:
    src: "{{ janus_install_dir }}"
    dest: "{{ janus_symlink }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
    force: yes

- name: Template JanusGraph configs
  template:
    src: "{{ item }}.j2"
    dest: "{{ janus_install_dir }}/{{ item }}"
  with_items:
    - conf/cassandra/cassandra.yaml
    - conf/cassandra/cassandra-rackdc.properties
    - conf/cassandra/cassandra-env.sh
    - conf/es/elasticsearch.yml
    - conf/gremlin-server/janusgraph-cassandra-es-server.properties
    - conf/gremlin-server/gremlin-server.yaml
    - conf/janusgraph-cassandra-es.properties
    - conf/log4j-console.properties
    - bin/janusgraph.sh
  tags: configs

- name: Tweak ulimits
  become: true
  template:
    src: "system/nofiles.conf.j2"
    dest: "/etc/security/limits.d/90-nofiles.conf"
